name: Node.js CD

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy website
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd ~/encryptlab
          git pull origin master
          git status
          npm install
          pm2 restart encryptlab